version: '3.9'

services:
  database:
    image: mysql
    platform: linux/x86_64
    container_name: rooms
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'rooms-secret'
      MYSQL_DATABASE: 'AlwaysFitRooms'
    ports:
      - '3306:3306'
